### ISSUE TITLE
IndexError: list assignment index out of range

### ISSUE THREAD

**Issue by dizhenx** [wujinzhong/Wav2Lip_TensorRT#5]
运行推理代码，用demo下面的samples里的game的mp4和wav推理没问题，换成别的mp4和wav推理就报错：
Traceback (most recent call last):
  File "inference.py", line 684, in <module>
    main()
  File "inference.py", line 561, in main
    face_det_results1 = cal_face_det_results(full_frames_tmp1, sfd_detector)
  File "inference.py", line 196, in cal_face_det_results
    face_det_results = face_detect(sfd_detector, frames) # BGR2RGB for CNN face detection
  File "inference.py", line 115, in face_detect
    images_list[i//batch_size] = np.array(images[i:i + batch_size])[...,::-1]
IndexError: list assignment index out of range

**Comment by dizhenx** [comment]
而且速度感觉比torch提升不明显，只提升了大约15%
